/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BBQControl;
import javax.swing.JFrame;
import model.AccompanimentToBBQ;
import model.GrillToBBQ;
import model.MeatToBBQ;
import model.SaladToBBQ;

/**
 *
 * @author Annette
 */
public class BasketItemPanel extends javax.swing.JPanel {

    private MeatToBBQ meatToBBQ;
    private AccompanimentToBBQ accompanimentToBBQ;
    private GrillToBBQ grillToBBQ;
    private SaladToBBQ saladToBBQ;
    private BBQControl bbqc;
    private int settings;

    /**
     * Creates new form BasketItemPanel
     */
    public BasketItemPanel(Object category, int settings) {
        this.settings = settings;
        bbqc = BBQControl.getInstance();
        initComponents();
        switch (category.getClass().getSimpleName()) {
            case "MeatToBBQ":
                meatToBBQ = (MeatToBBQ) category;
                jLType.setText(meatToBBQ.getMeat().getType());
                jLKilo.setText(meatToBBQ.getKilo() + " Kilo");
                jLPrice.setText(meatToBBQ.getTotalPrice() + " DKK");
                setSize(263, 59);
                break;
            case "AccompanimentToBBQ":
                accompanimentToBBQ = (AccompanimentToBBQ) category;
                jLType.setText(accompanimentToBBQ.getAccompaniment().getType());
                jLPrice.setText(accompanimentToBBQ.getTotalPrice(settings) + " DKK");
                jLKilo.setText("");
                setSize(263, 59);
                break;
            case "GrillToBBQ":
                grillToBBQ = (GrillToBBQ) category;
                jLType.setText(grillToBBQ.getGrill().getType());
                jLPrice.setText(grillToBBQ.getGrill().getCoalPrice() + " DKK");
                jLKilo.setText("");
                setSize(263, 59);
                break;
            case "SaladToBBQ":
                saladToBBQ = (SaladToBBQ) category;
                jLType.setText(saladToBBQ.getSalad().getType());
                jLPrice.setText(saladToBBQ.getTotalPrice(settings) + " DKK");
                jLKilo.setText("");
                setSize(263, 59);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLType = new javax.swing.JLabel();
        jLKilo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLPrice = new javax.swing.JLabel();

        setOpaque(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        jLType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLType.setText("jLabel1");
        add(jLType);
        jLType.setBounds(0, 0, 210, 22);

        jLKilo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLKilo.setText("jLabel2");
        add(jLKilo);
        jLKilo.setBounds(0, 30, 110, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(210, 0, 50, 50);

        jLPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLPrice.setText("jLabel3");
        add(jLPrice);
        jLPrice.setBounds(116, 30, 90, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        JFrame frame = new JFrame();
        SaladBarPanel saladBarPanel = new SaladBarPanel(frame, saladToBBQ.getSalad(), true);
        frame.add(saladBarPanel);
        frame.setSize(587, 335);
        frame.setVisible(true);
    }//GEN-LAST:event_formMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(meatToBBQ != null){
            bbqc.removeMeatFromList(meatToBBQ);
        } else if(accompanimentToBBQ != null){
            bbqc.removeAccompanimentFromList(accompanimentToBBQ);
        } else if(grillToBBQ != null){
            bbqc.removeGrillFromList(grillToBBQ);
        } else if(saladToBBQ != null){
            bbqc.removeSaladFromList(saladToBBQ);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLKilo;
    private javax.swing.JLabel jLPrice;
    private javax.swing.JLabel jLType;
    // End of variables declaration//GEN-END:variables
}
