/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Meat;
import model.MeatToBBQ;

/**
 *
 * @author Annette
 */
public class BasketItemPanel extends javax.swing.JPanel {

    private MeatToBBQ meatToBBQ;

    /**
     * Creates new form BasketItemPanel
     */
    public BasketItemPanel(Object category) {
        initComponents();
        switch (category.getClass().getSimpleName()) {
            case "MeatToBBQ":
                meatToBBQ = (MeatToBBQ) category;
                jLType.setText(meatToBBQ.getMeat().getType());
                jLKilo.setText(meatToBBQ.getKilo() + " Kilo");
                jLPrice.setText(meatToBBQ.getTotalPrice() + " DKK");
                setSize(263, 59);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLType = new javax.swing.JLabel();
        jLKilo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLPrice = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jLType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLType.setText("jLabel1");
        add(jLType);
        jLType.setBounds(0, 0, 210, 22);

        jLKilo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLKilo.setText("jLabel2");
        add(jLKilo);
        jLKilo.setBounds(0, 30, 110, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("X");
        add(jButton1);
        jButton1.setBounds(210, 0, 50, 50);

        jLPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLPrice.setText("jLabel3");
        add(jLPrice);
        jLPrice.setBounds(116, 30, 90, 22);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLKilo;
    private javax.swing.JLabel jLPrice;
    private javax.swing.JLabel jLType;
    // End of variables declaration//GEN-END:variables
}
