/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BBQControl;
import controller.SaladControl;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import model.Accompaniment;
import model.Grill;
import model.Meat;
import model.Salad;
import model.Vegetable;
import util.Listeners;

/**
 *
 * @author Annette
 */
public class CategoryButton extends javax.swing.JPanel implements ActionListener {

    private Meat meat;
    private Accompaniment accompaniment;
    private Grill grill;
    private BBQControl bbqc;
    private SaladControl saladControl;
    private CardLayout cl;
    private Salad salad;
    private Vegetable vegetable;
    private Listeners listener;
    private boolean isStandardVegetable;

    /**
     * Creates new form CategoryButton
     */
    public CategoryButton(Object category, boolean isStandardVegetable) {

        try {
            bbqc = BBQControl.getInstance();
            listener = Listeners.getList();
            saladControl = SaladControl.getInstance();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CategoryButton.class.getName()).log(Level.SEVERE, null, ex);
        }
        setSize(263, 30);
        initComponents();
        listener.addListener(this);
        cl = (CardLayout) getLayout();
        cl.addLayoutComponent(jPOther, "Other");
        cl.addLayoutComponent(jPMeat, "Meat");
        cl.addLayoutComponent(jPVegetable, "Vegetable");

        if (bbqc.getBuilder().getSettings() == 0) {
            jBType.setEnabled(false);
            jButton2.setEnabled(false);
            jToggleButton1.setEnabled(false);
        }
        switch (category.getClass().getSimpleName()) {
            case "Meat":
                meat = (Meat) category;
                cl.show(this, "Meat");
                jLMeatTitel.setText(meat.getType());
                setSize(263, 59);
                jButton2.setSize(this.getWidth(), jButton2.getHeight());
                jButton2.setLocation(0, (this.getHeight() - jButton2.getHeight()));
                this.repaint();
                this.revalidate();
                break;
            case "Accompaniment":
                accompaniment = (Accompaniment) category;
                cl.show(this, "Other");
                jBType.setText(accompaniment.getType());
                setSize(263, 30);
                jBType.setSize(getWidth(), getHeight());
                break;
            case "Grill":
                grill = (Grill) category;
                cl.show(this, "Other");
                jBType.setText(grill.getType());
                setSize(263, 30);
                jBType.setSize(getWidth(), getHeight());
                break;
            case "Salad":
                salad = (Salad) category;
                cl.show(this, "Other");
                jBType.setText(salad.getType());
                setSize(263, 30);
                jBType.setSize(getWidth(), getHeight());
                break;
            case "Vegetable":
                vegetable = (Vegetable) category;
                cl.show(this, "Vegetable");
                jToggleButton1.setText(vegetable.getType());
                setSize(180, 32);
                jToggleButton1.setSize(getWidth(), getHeight());
                if (isStandardVegetable) {
                    jToggleButton1.setSelected(isStandardVegetable);
                }
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPOther = new javax.swing.JPanel();
        jBType = new javax.swing.JButton();
        jPMeat = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLMeatTitel = new javax.swing.JLabel();
        jTKilo = new javax.swing.JTextField();
        jPVegetable = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setOpaque(false);
        setLayout(new java.awt.CardLayout());

        jBType.setBackground(new java.awt.Color(106, 140, 168));
        jBType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBType.setForeground(new java.awt.Color(255, 255, 255));
        jBType.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jBType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOtherLayout = new javax.swing.GroupLayout(jPOther);
        jPOther.setLayout(jPOtherLayout);
        jPOtherLayout.setHorizontalGroup(
            jPOtherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBType, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPOtherLayout.setVerticalGroup(
            jPOtherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBType, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        add(jPOther, "card3");

        jPMeat.setBackground(new java.awt.Color(106, 140, 168));
        jPMeat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPMeat.setForeground(new java.awt.Color(255, 255, 255));
        jPMeat.setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPMeat.add(jButton2);
        jButton2.setBounds(0, 30, 260, 31);

        jLMeatTitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLMeatTitel.setForeground(new java.awt.Color(255, 255, 255));
        jLMeatTitel.setText("Kød");
        jPMeat.add(jLMeatTitel);
        jLMeatTitel.setBounds(0, 0, 180, 28);

        jTKilo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTKilo.setText("Antal Kilo");
        jTKilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTKiloActionPerformed(evt);
            }
        });
        jTKilo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTKiloFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTKiloFocusGained(evt);
            }
        });
        jPMeat.add(jTKilo);
        jTKilo.setBounds(180, 0, 81, 28);

        add(jPMeat, "card4");

        jToggleButton1.setBackground(new java.awt.Color(106, 140, 168));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Grønsag");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPVegetableLayout = new javax.swing.GroupLayout(jPVegetable);
        jPVegetable.setLayout(jPVegetableLayout);
        jPVegetableLayout.setHorizontalGroup(
            jPVegetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPVegetableLayout.setVerticalGroup(
            jPVegetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        add(jPVegetable, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void jTKiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTKiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTKiloActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            int kilo = Integer.parseInt(jTKilo.getText());

            if (jLMeatTitel.getText().equals("Hel gris 0-35 kg")) {
                if (kilo >= 0 && kilo <= 35) {
                    bbqc.addMeatToList(meat, Integer.parseInt(jTKilo.getText()));
                    jButton2.setText("OK");
                    jButton2.setForeground(Color.black);
                } else {
                    jButton2.setText("Forkert antal kilo!");
                    jButton2.setForeground(Color.red);
                }
            } else if (jLMeatTitel.getText().equals("Hel gris 35-50 kg")) {
                if (kilo >= 35 && kilo <= 50) {
                    bbqc.addMeatToList(meat, Integer.parseInt(jTKilo.getText()));
                    jButton2.setText("OK");
                    jButton2.setForeground(Color.black);
                } else {
                    jButton2.setText("Forkert antal kilo!");
                    jButton2.setForeground(Color.red);
                }
            } else if (jLMeatTitel.getText().equals("Hel gris 50-90 kg")) {
                if (kilo >= 50) {
                    bbqc.addMeatToList(meat, Integer.parseInt(jTKilo.getText()));
                    jButton2.setText("OK");
                    jButton2.setForeground(Color.black);
                } else {
                    jButton2.setText("Forkert antal kilo!");
                    jButton2.setForeground(Color.red);
                }
            } else {
                bbqc.addMeatToList(meat, Integer.parseInt(jTKilo.getText()));
                jButton2.setText("OK");
                jButton2.setForeground(Color.black);
            }
        } catch (NumberFormatException ex) {
            System.out.println("fejl i at få kilo til tal");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTKiloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTKiloFocusGained
        if (jTKilo.getText().equals("Antal Kilo")) {
            jTKilo.setText("");
        }
    }//GEN-LAST:event_jTKiloFocusGained

    private void jBTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTypeActionPerformed
        if (accompaniment != null) {
            bbqc.addAccompanimentToList(accompaniment);
        } else if (grill != null) {
            bbqc.addGrillToList(grill);
        } else if (salad != null) {
            if (salad.getType().equals("Salatbar")) {
                JFrame frame = new JFrame();
                SaladBarPanel saladBarPanel = new SaladBarPanel(frame, salad, false);
                frame.add(saladBarPanel);
                frame.setSize(587, 335);
                frame.setVisible(true);
                System.out.println("sgsgseg");

            } else {
                bbqc.addSaladToList(salad);
            }
        }
    }//GEN-LAST:event_jBTypeActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()) {
            saladControl.addToSaladBar(vegetable);
        } else {
            saladControl.removeFromSaladBar(vegetable);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTKiloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTKiloFocusLost
        if (jTKilo.getText().equals("")) {
            jTKilo.setText("Antal Kilo");
        }
    }//GEN-LAST:event_jTKiloFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBType;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLMeatTitel;
    private javax.swing.JPanel jPMeat;
    private javax.swing.JPanel jPOther;
    private javax.swing.JPanel jPVegetable;
    private javax.swing.JTextField jTKilo;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        switch (ae.getActionCommand()) {
            case "settings added":
                jBType.setEnabled(true);
                jButton2.setEnabled(true);
                jToggleButton1.setEnabled(true);
                break;
            case "settings removed":
                jBType.setEnabled(false);
                jButton2.setEnabled(false);
                jToggleButton1.setEnabled(false);
                break;
        }
    }
}
