/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.BBQControl;
import java.awt.CardLayout;
import model.Meat;

/**
 *
 * @author Annette
 */
public class CategoryButton extends javax.swing.JPanel {

    private Meat meat;
    private BBQControl bbqc;
    private CardLayout cl;

    /**
     * Creates new form CategoryButton
     */
    public CategoryButton(Object category) {
        bbqc = BBQControl.getInstance();
        setSize(263, 30);
        initComponents();
        cl = (CardLayout) getLayout();
        cl.addLayoutComponent(jPOther, "Other");
        cl.addLayoutComponent(jPMeat, "Meat");
        switch (category.getClass().getSimpleName()) {
            case "Meat":
                meat = (Meat) category;
                cl.show(this, "Meat");
                jLMeatTitel.setText(meat.getType());
                setSize(263, 59);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPOther = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPMeat = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLMeatTitel = new javax.swing.JLabel();
        jTKilo = new javax.swing.JTextField();

        setOpaque(false);
        setLayout(new java.awt.CardLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPOtherLayout = new javax.swing.GroupLayout(jPOther);
        jPOther.setLayout(jPOtherLayout);
        jPOtherLayout.setHorizontalGroup(
            jPOtherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPOtherLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPOtherLayout.setVerticalGroup(
            jPOtherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPOtherLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPOther, "card3");

        jPMeat.setOpaque(false);
        jPMeat.setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPMeat.add(jButton2);
        jButton2.setBounds(0, 30, 260, 31);

        jLMeatTitel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLMeatTitel.setText("Kød");
        jPMeat.add(jLMeatTitel);
        jLMeatTitel.setBounds(0, 0, 180, 28);

        jTKilo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTKilo.setText("Antal Kilo");
        jTKilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTKiloActionPerformed(evt);
            }
        });
        jTKilo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTKiloFocusGained(evt);
            }
        });
        jPMeat.add(jTKilo);
        jTKilo.setBounds(180, 0, 81, 28);

        add(jPMeat, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void jTKiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTKiloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTKiloActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        bbqc.addMeatToList(meat, Integer.parseInt(jTKilo.getText()));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTKiloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTKiloFocusGained
        if (jTKilo.getText().equals("Antal Kilo")) {
            jTKilo.setText("");
        }
    }//GEN-LAST:event_jTKiloFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLMeatTitel;
    private javax.swing.JPanel jPMeat;
    private javax.swing.JPanel jPOther;
    private javax.swing.JTextField jTKilo;
    // End of variables declaration//GEN-END:variables
}
