/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ErrorControl;
import controller.MassageControl;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import util.Listeners;

/**
 *
 * @author Mark
 */
public class EditMassagePanel extends javax.swing.JPanel {

    private MassageControl masControl;
    private int id;
    private String type;
    private int price;
    private int duration;
    private Listeners listener;
    private ErrorControl errorControl;

    /**
     * Creates new form EditMassagePanel
     */
    public EditMassagePanel(int id1, String type1, int price1, int duration1) {
        this.setSize(380, 50);
        this.id = id1;
        this.type = type1;
        this.price = price1;
        this.duration = duration1;
        listener = Listeners.getList();
        try {
            errorControl = ErrorControl.getInstance();
            masControl = MassageControl.getInstance();
        } catch (ClassNotFoundException | SQLException ex) {
            try {
                errorControl.createErrorPopup("Fejl i forbindelse til databasen.", ex.getLocalizedMessage());
            } catch (SQLException ex1) {
                System.out.println(ex1.getLocalizedMessage());
            }
        }
        initComponents();
        jT_masType.setText(type);
        jT_masPrice.setText(price + "");
        jT_masDur.setText(duration + "");

    }

    public void saveMassage() {
        price = Integer.parseInt(jT_masPrice.getText());
        duration = Integer.parseInt(jT_masDur.getText());
        try {
            masControl.editMassageType(id, price, duration);
        } catch (SQLException ex) {
            try {
                errorControl.createErrorPopup("Fejl i forbindelse til databasen.", ex.getLocalizedMessage());
            } catch (SQLException ex1) {
                System.out.println(ex1.getLocalizedMessage());
            }
        }
        listener.notifyListeners("New Event Created");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_masType = new javax.swing.JTextField();
        jT_masPrice = new javax.swing.JTextField();
        jT_masDur = new javax.swing.JTextField();

        jLabel1.setText("Massage Type:");

        jLabel2.setText("Massage Pris:");

        jLabel3.setText("Massage Varighed:");

        jT_masType.setEditable(false);

        jT_masPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_masPriceFocusLost(evt);
            }
        });

        jT_masDur.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_masDurFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jT_masType, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jT_masPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jT_masDur)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_masType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_masPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_masDur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jT_masPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_masPriceFocusLost
        saveMassage();
    }//GEN-LAST:event_jT_masPriceFocusLost

    private void jT_masDurFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_masDurFocusLost
        saveMassage();
    }//GEN-LAST:event_jT_masDurFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jT_masDur;
    private javax.swing.JTextField jT_masPrice;
    private javax.swing.JTextField jT_masType;
    // End of variables declaration//GEN-END:variables
}
