/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SaladControl;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JToggleButton;
import model.Vegetable;

/**
 *
 * @author Annette
 */
public class SaladBarPanel extends javax.swing.JPanel {

    private ArrayList<Vegetable> vegetables;
    private ArrayList<String> standardVegetables;
    private SaladControl saladControl;
    private JFrame frame;

    /**
     * Creates new form SaladBarPanel
     */
    public SaladBarPanel(JFrame frame, ArrayList<String> standardVegetables) {
        try {
            this.frame = frame;
            saladControl = SaladControl.getInstance();
            vegetables = saladControl.getVegetableList();
            this.standardVegetables = standardVegetables;
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SaladBarPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        showVegetables();
    }

    public void showVegetables() {
        int location = 0;
        int row = 0;
        int panelWidth = 0;
        for (Vegetable vegetable : vegetables) {
            boolean isStandardVegetable = false;
            for (String standardVegetable : standardVegetables) {
                if (vegetable.getType().equals(standardVegetable)) {
                    isStandardVegetable = true;
                }
            }
            CategoryButton vegetableButton = new CategoryButton((Object) vegetable, isStandardVegetable);
            vegetableButton.setLocation((row * vegetableButton.getWidth()) + (5 * row), (5 * location + 10) + (vegetableButton.getHeight() * location));
            jPSaladBar.add(vegetableButton);
            vegetableButton.setVisible(true);
            panelWidth = row * vegetableButton.getWidth();
            jPSaladBar.setPreferredSize(new Dimension(panelWidth, (5 * 5 + 10) + (vegetableButton.getHeight() * 5)));
            location++;
            if (location == 5) {
                location = 0;
                row++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPSaladBar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grønsager til Salatbar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPSaladBar.setOpaque(false);

        javax.swing.GroupLayout jPSaladBarLayout = new javax.swing.GroupLayout(jPSaladBar);
        jPSaladBar.setLayout(jPSaladBarLayout);
        jPSaladBarLayout.setHorizontalGroup(
            jPSaladBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );
        jPSaladBarLayout.setVerticalGroup(
            jPSaladBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPSaladBar);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(6, 24, 560, 220);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("OK");
        jPanel1.add(jButton1);
        jButton1.setBounds(240, 250, 110, 40);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 570, 300);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPSaladBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
